apiVersion: v1
items:
- apiVersion: elasticsearch.k8s.elastic.co/v1
  kind: Elasticsearch
  metadata:
    name: quickstart
  spec:
    http:
      service:
        metadata:
          creationTimestamp: null
        spec: {}
      tls:
        certificate: {}
    nodeSets:
    - config:
        node.data: false
        node.ingest: true
        node.master: true
        node.store.allow_mmap: false
      count: {{ .Values.nodeSets.master.count }}
      name: master
      podTemplate:
        metadata: {}
        spec:
          containers:
          - env:
            - name: ES_JAVA_OPTS
              value: -Xms1024M -Xmx1024M
            name: elasticsearch
            resources:
              limits:
                cpu: "2"
                memory: 2Gi
              requests:
                cpu: "1"
                memory: 1Gi
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - config:
        node.data: true
        node.ingest: true
        node.master: false
        node.store.allow_mmap: false
      count: {{ .Values.nodeSets.data.count }}
      name: data20g
      podTemplate:
        metadata: {}
        spec:
          containers:
          - env:
            - name: ES_JAVA_OPTS
              value: -Xms1024M -Xmx1024M
            name: elasticsearch
            resources:
              limits:
                cpu: "2"
                memory: 2Gi
              requests:
                cpu: "1"
                memory: 1Gi
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
    updateStrategy:
      changeBudget: {}
    version: 7.6.2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""    