apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  annotations:
    association.k8s.elastic.co/es-conf: '{"authSecretName":"quickstart-kibana-user","authSecretKey":"default-quickstart-kibana-user","caCertProvided":true,"caSecretName":"quickstart-kb-es-ca","url":"https://quickstart-es-http.default.svc:9200"}'
    common.k8s.elastic.co/controller-version: 1.0.1
  name: quickstart
  namespace: default
spec:
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
    tls:
      certificate: {}
  podTemplate:
    metadata:
      creationTimestamp: null
    spec:
      containers: null
  version: 7.6.2
