apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: composite-helm
  name: composite-helm
  namespace: default
spec:
  selector:
    app: composite-helm
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    - port: 6568
      protocol: TCP
      targetPort: 6568
  sessionAffinity: None
  type: ClusterIP
