apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: core-helm
  name: monitoringcore
  namespace: default
spec:
  selector:
    app: core-helm
  ports:
    - port: 8070
      protocol: TCP
      targetPort: 8070
      name: rest
    - port: 6569
      protocol: TCP
      targetPort: 6569
      name: grpc
  sessionAffinity: None
  type: ClusterIP
